### ISSUE TITLE
CAN bus or MOST

### ISSUE THREAD

**Issue by RiLights** [johnbutol/CCM-busmaster#1]
Hi,

I saw that you mentioning about CAN bus but I read that Volvo uses MOST bust, correct me please if I'm wrong.

Thanks
Ostap

**Comment by johnbutol** [comment]
They use both! Worse, they use LIN bus also. M in MOST stands for media so all audio related content use this interface. As CCM controls also HVAC, CANBus is used. LIN bus just provides the steering wheel control.

**Comment by RiLights** [comment]
Thanks for a explanation!
